automatic_scaling: 
  cool_down_period_sec: 120
  max_num_instances: 10
  min_num_instances: 1
env: flex
network: 
  forwarded_ports: 
    - 80:8080
resources: 
  cpu: 1
  disk_size_gb: 10
  memory_gb: 2
runtime: custom
service: default
threadsafe: true
